replicaCount: 1

deployment: 
  name: "mydeploy"
  label: "mydeploy"

image:
  repository: kareemelkasaby/itimansbakehouse
  tag: "7"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  port2: 6379

resources: 
  containers:
    image: kareemelkasaby/itimansbakehouse:7
    name:  mydeploy
    

autoscaling:
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

 