apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label}}
    spec:
      containers:
        - name: {{ .Values.resources.containers.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources: {}