apiVersion: v1
kind: Service
metadata: 
  name: myservice
  labels:
    app: myservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 30215
  
  selector:
    app: {{ .Values.deployment.name }}
status:
  loadBalancer: {}
